name: tienda_control
description: Aplicación de inventario y ventas para tienda de barrio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Navegación y estado
  go_router: ^12.1.1
  provider: ^6.0.5
  
  # Base de datos y almacenamiento
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Internacionalización y formato
  intl: ^0.18.1
  
  # Scanner de códigos
  mobile_scanner: ^3.5.2
  
  # UI e iconos
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets de la aplicación
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/