// lib/core/constants/app_languages.dart
class AppLanguages {
  // Prevenir instanciación
  AppLanguages._();

  // Constantes de configuración
  static const String defaultLanguage = 'es';
  static const List<String> supportedLanguages = ['es', 'en', 'it'];
  
  // Información de idiomas
  static const Map<String, LanguageInfo> languageInfo = {
    'es': LanguageInfo('Español', '🇪🇸'),
    'en': LanguageInfo('English', '🇬🇧'),
    'it': LanguageInfo('Italiano', '🇮🇹'),
  };

  // Cache para traducciones cargadas
  static final Map<String, Map<String, String>> _translationsCache = {};

  // Obtener traducción con fallback
  static String translate(String languageCode, String key) {
    // Asegurar que el idioma esté cargado
    _ensureLanguageLoaded(languageCode);
    
    // Buscar traducción
    final translation = _translationsCache[languageCode]?[key];
    if (translation != null) return translation;
    
    // Fallback al idioma por defecto
    if (languageCode != defaultLanguage) {
      _ensureLanguageLoaded(defaultLanguage);
      final defaultTranslation = _translationsCache[defaultLanguage]?[key];
      if (defaultTranslation != null) return defaultTranslation;
    }
    
    // Si no hay traducción, devolver la key formateada
    return _formatKey(key);
  }

  // Formatear key cuando no hay traducción disponible
  static String _formatKey(String key) {
    return key.replaceAll('_', ' ').split(' ').map((word) {
      if (word.isEmpty) return word;
      return word[0].toUpperCase() + word.substring(1);
    }).join(' ');
  }

  // Cargar idioma si no está en cache
  static void _ensureLanguageLoaded(String languageCode) {
    if (!_translationsCache.containsKey(languageCode)) {
      switch (languageCode) {
        case 'es':
          _translationsCache['es'] = _spanishTranslations;
          break;
        case 'en':
          _translationsCache['en'] = _englishTranslations;
          break;
        case 'it':
          _translationsCache['it'] = _italianTranslations;
          break;
        default:
          _translationsCache[languageCode] = _spanishTranslations; // Fallback
      }
    }
  }

  // Precargar un idioma específico
  static void preloadLanguage(String languageCode) {
    _ensureLanguageLoaded(languageCode);
  }

  // Precargar todos los idiomas
  static void preloadAllLanguages() {
    for (final lang in supportedLanguages) {
      _ensureLanguageLoaded(lang);
    }
  }

  // Limpiar cache
  static void clearCache() {
    _translationsCache.clear();
  }

  // Verificar si un idioma está soportado
  static bool isSupported(String languageCode) {
    return supportedLanguages.contains(languageCode);
  }

  // Obtener información del idioma
  static LanguageInfo? getLanguageInfo(String languageCode) {
    return languageInfo[languageCode];
  }

  // TRADUCCIONES COMPLETAS
  
  // ESPAÑOL
  static const Map<String, String> _spanishTranslations = {
    // === CONFIGURACIÓN DE IDIOMA ===
    'language': 'Idioma',
    'change_language': 'Cambiar Idioma',
    'select_language': 'Seleccionar Idioma',
    'language_changed': 'Idioma cambiado',
    'language_changed_successfully': 'El idioma se cambió exitosamente',
    'error_changing_language': 'Error al cambiar el idioma',
    'language_settings': 'Configuración de Idioma',
    'current_language': 'Idioma Actual',
    'available_languages': 'Idiomas Disponibles',
    'language_selection': 'Selección de Idioma',
    'choose_preferred_language': 'Elige tu idioma preferido',
    'language_will_be_saved': 'Tu selección de idioma se guardará automáticamente',
    'restart_app_language': 'Reinicia la app para aplicar completamente el cambio',
    'language_applied': 'Idioma aplicado',
    'loading_language': 'Cargando idioma...',
    'language_not_available': 'Idioma no disponible',
    'default_language_loaded': 'Se cargó el idioma por defecto',
    'language_system_error': 'Error en el sistema de idiomas',
    'language_preferences': 'Preferencias de Idioma',
    'auto_detect_language': 'Detectar automáticamente',
    'system_language': 'Idioma del sistema',
    'app_language': 'Idioma de la aplicación',
    'language_support': 'Soporte de idiomas',
    'multilingual_support': 'Soporte multiidioma',
    'language_pack': 'Paquete de idioma',
    'translation_loading': 'Cargando traducciones...',
    'translation_error': 'Error en la traducción',
    'fallback_language': 'Idioma de respaldo',
    'language_code': 'Código de idioma',
    'locale_settings': 'Configuración regional',
    'regional_format': 'Formato regional',
    'date_format': 'Formato de fecha',
    'number_format': 'Formato numérico',
    'currency_format': 'Formato de moneda',
    'time_format': 'Formato de hora',
    
    // === NOMBRES DE IDIOMAS ===
    'spanish': 'Español',
    'english': 'Inglés',
    'italian': 'Italiano',
    'spanish_spain': 'Español (España)',
    'english_us': 'Inglés (Estados Unidos)',
    'english_uk': 'Inglés (Reino Unido)',
    'italian_italy': 'Italiano (Italia)',
    
    // === MENSAJES DEL SISTEMA ===
    'loading': 'Cargando...',
    'loading_data': 'Cargando datos...',
    'initializing': 'Inicializando...',
    'please_wait': 'Por favor espera...',
    'processing': 'Procesando...',
    'saving': 'Guardando...',
    'loading_preferences': 'Cargando preferencias...',
    'applying_changes': 'Aplicando cambios...',
    'updating_interface': 'Actualizando interfaz...',
    'preparing_content': 'Preparando contenido...',
    'loading_configuration': 'Cargando configuración...',
    
    // === ACCIONES DE BOTONES ===
    'close': 'Cerrar',
    'cancel': 'Cancelar',
    'accept': 'Aceptar',
    'ok': 'Ok',
    'save': 'Guardar',
    'apply': 'Aplicar',
    'confirm': 'Confirmar',
    'continue': 'Continuar',
    'back': 'Atrás',
    'next': 'Siguiente',
    'finish': 'Finalizar',
    'done': 'Hecho',
    'skip': 'Omitir',
    'retry': 'Reintentar',
    'refresh': 'Actualizar',
    'reload': 'Recargar',
    'reset': 'Restablecer',
    'clear': 'Limpiar',
    'delete': 'Eliminar',
    'edit': 'Editar',
    'view': 'Ver',
    'select': 'Seleccionar',
    'choose': 'Elegir',
    'pick': 'Escoger',
    'set': 'Establecer',
    'change': 'Cambiar',
    'modify': 'Modificar',
    'update': 'Actualizar',
    'view_all': 'Ver todo',
    
    // === ESTADOS Y VALIDACIONES ===
    'success': 'Éxito',
    'error': 'Error',
    'warning': 'Advertencia',
    'info': 'Información',
    'completed': 'Completado',
    'failed': 'Falló',
    'pending': 'Pendiente',
    'in_progress': 'En progreso',
    'cancelled': 'Cancelado',
    'timeout': 'Tiempo agotado',
    'unavailable': 'No disponible',
    'not_found': 'No encontrado',
    'invalid': 'Inválido',
    'valid': 'Válido',
    'required_field': 'Requerido',
    'optional_field': 'Opcional',
    'enabled': 'Habilitado',
    'disabled': 'Deshabilitado',
    'active': 'Activo',
    'inactive': 'Inactivo',
    'online': 'En línea',
    'offline': 'Sin conexión',
    'connected': 'Conectado',
    'disconnected': 'Desconectado',
    'synchronized': 'Sincronizado',
    'not_synchronized': 'No sincronizado',
    'sent': 'Enviado',
    
    // === MENSAJES DE ERROR ESPECÍFICOS ===
    'error_occurred': 'Ha ocurrido un error',
    'unexpected_error': 'Error inesperado',
    'connection_error': 'Error de conexión',
    'network_error': 'Error de red',
    'server_error': 'Error del servidor',
    'data_error': 'Error de datos',
    'permission_error': 'Error de permisos',
    'configuration_error': 'Error de configuración',
    'initialization_error': 'Error de inicialización',
    'validation_error': 'Error de validación',
    'format_error': 'Error de formato',
    'compatibility_error': 'Error de compatibilidad',
    'version_error': 'Error de versión',
    'memory_error': 'Error de memoria',
    'storage_error': 'Error de almacenamiento',
    'file_error': 'Error de archivo',
    'database_error': 'Error de base de datos',
    'sync_error': 'Error de sincronización',
    'backup_error': 'Error de respaldo',
    'restore_error': 'Error de restauración',
    'import_error': 'Error de importación',
    'export_error': 'Error de exportación',
    'parse_error': 'Error de análisis',
    'rendering_error': 'Error de renderización',
    'calculation_error': 'Error de cálculo',
    'conversion_error': 'Error de conversión',
    'error_loading_data': 'Error al cargar datos',
    'no_data_available': 'No hay datos disponibles',
    'try_refresh': 'Intenta actualizar los datos',
    
    // === CONFIGURACIÓN Y PREFERENCIAS ===
    'settings': 'Configuración',
    'preferences': 'Preferencias',
    'options': 'Opciones',
    'configuration': 'Configuración',
    'setup': 'Configuración inicial',
    'customization': 'Personalización',
    'appearance': 'Apariencia',
    'behavior': 'Comportamiento',
    'notifications': 'Notificaciones',
    'privacy': 'Privacidad',
    'security': 'Seguridad',
    'accessibility': 'Accesibilidad',
    'advanced': 'Avanzado',
    'general': 'General',
    'account': 'Cuenta',
    'profile': 'Perfil',
    'user_settings': 'Configuración de usuario',
    'app_settings': 'Configuración de la app',
    'system_settings': 'Configuración del sistema',
    'default_settings': 'Configuración por defecto',
    'restore_defaults': 'Restaurar valores por defecto',
    'save_settings': 'Guardar configuración',
    'settings_saved': 'Configuración guardada',
    'settings_restored': 'Configuración restaurada',
    'unsaved_changes': 'Cambios sin guardar',
    'save_changes_question': '¿Guardar los cambios?',
    'discard_changes': 'Descartar cambios',
    'changes_will_be_lost': 'Los cambios se perderán',
    
    // === ACCESIBILIDAD ===
    'accessibility_enabled': 'Accesibilidad habilitada',
    'high_contrast': 'Alto contraste',
    'large_text': 'Texto grande',
    'screen_reader': 'Lector de pantalla',
    'voice_over': 'VoiceOver',
    'talk_back': 'TalkBack',
    'font_size': 'Tamaño de fuente',
    'text_size': 'Tamaño del texto',
    'zoom_level': 'Nivel de zoom',
    'contrast_level': 'Nivel de contraste',
    'brightness': 'Brillo',
    'color_blind_support': 'Soporte para daltonismo',
    'reduced_motion': 'Movimiento reducido',
    'audio_descriptions': 'Descripciones de audio',
    'captions': 'Subtítulos',
    'sign_language': 'Lenguaje de señas',
    
    // === AYUDA Y SOPORTE ===
    'help': 'Ayuda',
    'support': 'Soporte',
    'documentation': 'Documentación',
    'tutorial': 'Tutorial',
    'guide': 'Guía',
    'faq': 'Preguntas frecuentes',
    'contact': 'Contacto',
    'feedback': 'Comentarios',
    'report_bug': 'Reportar error',
    'suggest_feature': 'Sugerir función',
    'user_manual': 'Manual de usuario',
    'quick_start': 'Inicio rápido',
    'getting_started': 'Primeros pasos',
    'tips_and_tricks': 'Consejos y trucos',
    'troubleshooting': 'Solución de problemas',
    'known_issues': 'Problemas conocidos',
    'release_notes': 'Notas de la versión',
    'changelog': 'Registro de cambios',
    'version_info': 'Información de versión',
    'about': 'Acerca de',
    'legal': 'Legal',
    'terms_of_service': 'Términos de servicio',
    'privacy_policy': 'Política de privacidad',
    'license': 'Licencia',
    'credits': 'Créditos',
    'acknowledgments': 'Reconocimientos',
    
    // === DASHBOARD Y NAVEGACIÓN ===
    'dashboard': 'Panel Principal',
    'home': 'Inicio',
    'menu': 'Menú',
    'navigation': 'Navegación',
    'sidebar': 'Barra lateral',
    'toolbar': 'Barra de herramientas',
    'header': 'Encabezado',
    'footer': 'Pie de página',
    'main_content': 'Contenido principal',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'sort': 'Ordenar',
    'group': 'Agrupar',
    'categories': 'Categorías',
    'tags': 'Etiquetas',
    'favorites': 'Favoritos',
    'bookmarks': 'Marcadores',
    'recent': 'Reciente',
    'history': 'Historial',
    'activity': 'Actividad',
    'timeline': 'Línea de tiempo',
    'calendar': 'Calendario',
    'schedule': 'Horario',
    'agenda': 'Agenda',
    'events': 'Eventos',
    'reminders': 'Recordatorios',
    'alerts': 'Alertas',
    'notifications_panel': 'Panel de notificaciones',
    'status_bar': 'Barra de estado',
    'progress_bar': 'Barra de progreso',
    'loading_indicator': 'Indicador de carga',
    'spinner': 'Indicador giratorio',
    
    // === TIEMPO Y FECHAS ===
    'today': 'Hoy',
    'yesterday': 'Ayer',
    'tomorrow': 'Mañana',
    'this_week': 'Esta semana',
    'last_week': 'Semana pasada',
    'next_week': 'Próxima semana',
    'this_month': 'Este mes',
    'last_month': 'Mes pasado',
    'next_month': 'Próximo mes',
    'this_year': 'Este año',
    'last_year': 'Año pasado',
    'next_year': 'Próximo año',
    'now': 'Ahora',
    'ago': 'hace',
    'in': 'en',
    'seconds': 'segundos',
    'minutes': 'minutos',
    'hours': 'horas',
    'days': 'días',
    'weeks': 'semanas',
    'months': 'meses',
    'years': 'años',
    'second': 'segundo',
    'minute': 'minuto',
    'hour': 'hora',
    'day': 'día',
    'week': 'semana',
    'month': 'mes',
    'year': 'año',
    'morning': 'mañana',
    'afternoon': 'tarde',
    'evening': 'noche',
    'night': 'noche',
    'midnight': 'medianoche',
    'noon': 'mediodía',
    'dawn': 'amanecer',
    'dusk': 'atardecer',
    'sunrise': 'amanecer',
    'sunset': 'atardecer',
    
    // === DÍAS DE LA SEMANA ===
    'monday': 'Lunes',
    'tuesday': 'Martes',
    'wednesday': 'Miércoles',
    'thursday': 'Jueves',
    'friday': 'Viernes',
    'saturday': 'Sábado',
    'sunday': 'Domingo',
    'mon': 'Lun',
    'tue': 'Mar',
    'wed': 'Mié',
    'thu': 'Jue',
    'fri': 'Vie',
    'sat': 'Sáb',
    'sun': 'Dom',
    
    // === MESES ===
    'january': 'Enero',
    'february': 'Febrero',
    'march': 'Marzo',
    'april': 'Abril',
    'may': 'Mayo',
    'june': 'Junio',
    'july': 'Julio',
    'august': 'Agosto',
    'september': 'Septiembre',
    'october': 'Octubre',
    'november': 'Noviembre',
    'december': 'Diciembre',
    'jan': 'Ene',
    'feb': 'Feb',
    'mar': 'Mar',
    'apr': 'Abr',
    'may_short': 'May',
    'jun': 'Jun',
    'jul': 'Jul',
    'aug': 'Ago',
    'sep': 'Set',
    'oct': 'Oct',
    'nov': 'Nov',
    'dec': 'Dic',
    
    // === APP ESPECÍFICO ===
    'app_name': 'Mi Inventario',
    'welcome': 'Bienvenido',
    'good_morning': 'Buenos días',
    'good_afternoon': 'Buenas tardes',
    'good_evening': 'Buenas noches',
    'products': 'Productos',
    'inventory': 'Inventario',
    'sales': 'Ventas',
    'reports': 'Reportes',
    'point_of_sale': 'Punto de Venta',
    'settings_app': 'Configuración',
    
    // === DASHBOARD ESPECÍFICO ===
    'today_summary': 'Resumen de Hoy',
    'sales_today': 'Ventas de Hoy',
    'active_products': 'productos activos',
    'low_stock': 'Stock Bajo',
    'require_attention': 'requieren atención',
    'detailed_analysis': 'análisis detallado',
    'quick_actions': 'Acciones Rápidas',
    'new_sale': 'Nueva Venta',
    'add_product': 'Agregar Producto',
    'recent_sales': 'Ventas Recientes',
    'no_sales_recorded': 'No hay ventas registradas',
    'sales_will_appear': 'Las ventas aparecerán aquí cuando se registren',
    'system_working': 'Sistema funcionando',
    'store_ready': 'La tienda está lista para operar',
    
    // === PRODUCTOS ESPECÍFICO ===
    'my_products': 'Mis Productos',
    'product_name': 'Nombre del Producto',
    'product_description': 'Descripción del Producto',
    'category': 'Categoría',
    'no_category': 'Sin categoría',
    'select_category': 'Seleccionar categoría',
    'barcode': 'Código de Barras',
    'internal_code': 'Código Interno',
    'purchase_price': 'Precio de Compra',
    'sale_price': 'Precio de Venta',
    'cost_price': 'Precio de Costo',
    'unit_measure': 'Unidad de Medida',
    'minimum_stock': 'Stock Mínimo',
    'current_stock': 'Stock Actual',
    'initial_quantity': 'Cantidad Inicial',
    'product_information': 'Información del Producto',
    'stock_information': 'Información de Stock',
    'price_information': 'Información de Precios',
    'code': 'Código',
    'description': 'Descripción',
    'unit': 'Unidad',
    'stock': 'Stock',
    'price': 'Precio',
    'margin': 'Margen',
    'profit_margin': 'Margen de Ganancia',
    'stock_warning': 'Alerta de Stock',
    'low_stock_warning': 'Stock por debajo del mínimo recomendado',
    'out_of_stock': 'Sin Stock',
    'stock_ok': 'Stock Normal',
    'in_stock': 'Con Stock',
    'stock_status': 'Estado del Stock',
    'add_stock': 'Agregar Stock',
    'edit_product': 'Editar Producto',
    'new_product': 'Nuevo Producto',
    'create_product': 'Crear Producto',
    'update_product': 'Actualizar Producto',
    'delete_product': 'Eliminar Producto',
    'scan_barcode': 'Escanear Código',
    'enter_barcode': 'Ingresar Código',
    'no_products_found': 'No se encontraron productos',
    'no_products_registered': 'No hay productos registrados',
    'search_products': 'Buscar productos',
    'filter_products': 'Filtrar productos',
    'all_products': 'Todos los productos',
    'low_stock_products': 'Productos con stock bajo',
    'out_of_stock_products': 'Productos sin stock',
    'sort_by_name': 'Ordenar por nombre',
    'sort_by_stock': 'Ordenar por stock',
    'sort_by_price': 'Ordenar por precio',
    'clear_filters': 'Limpiar filtros',
    'apply_filters': 'Aplicar filtros',
    'product_created': 'Producto creado exitosamente',
    'product_updated': 'Producto actualizado exitosamente',
    'product_deleted': 'Producto eliminado exitosamente',
    'error_creating_product': 'Error al crear el producto',
    'error_updating_product': 'Error al actualizar el producto',
    'error_deleting_product': 'Error al eliminar el producto',
    'product_details': 'Detalles del Producto',
    'basic_information': 'Información Básica',
    'pricing': 'Precios',
    'stock_configuration': 'Configuración de Stock',
    'unsaved_changes_product': 'Tienes cambios sin guardar',
    'discard_changes_product': '¿Descartar cambios?',
    'save_changes_product': '¿Guardar cambios?',
    'continue_editing': 'Continuar editando',
    'add_first_product': 'Agregar primer producto',
    'start_managing_inventory': 'Comienza a gestionar tu inventario',
    'product_codes': 'Códigos del Producto',
    'expiration_date': 'Fecha de Vencimiento',
    'select_date': 'Seleccionar fecha',
    'remove_date': 'Quitar fecha',
    'notes': 'Notas',
    'observations': 'Observaciones',
    'batch_number': 'Número de Lote',
    'batch_code': 'Código de Lote',
    'batches': 'Lotes',
    'no_batches': 'Sin lotes',
    'add_batch': 'Agregar Lote',
    'expires': 'Vence',
    'expired': 'Vencido',
    'near_expiry': 'Próximo a vencer',
    'days_to_expire': 'días para vencer',
    'expires_today': 'Vence hoy',
    'expires_tomorrow': 'Vence mañana',
    'no_expiration': 'Sin fecha de vencimiento',
  };

  // ENGLISH
  static const Map<String, String> _englishTranslations = {
    // === LANGUAGE CONFIGURATION ===
    'language': 'Language',
    'change_language': 'Change Language',
    'select_language': 'Select Language',
    'language_changed': 'Language changed',
    'language_changed_successfully': 'Language changed successfully',
    'error_changing_language': 'Error changing language',
    'language_settings': 'Language Settings',
    'current_language': 'Current Language',
    'available_languages': 'Available Languages',
    'language_selection': 'Language Selection',
    'choose_preferred_language': 'Choose your preferred language',
    'language_will_be_saved': 'Your language selection will be saved automatically',
    'restart_app_language': 'Restart the app to fully apply the change',
    'language_applied': 'Language applied',
    'loading_language': 'Loading language...',
    'language_not_available': 'Language not available',
    'default_language_loaded': 'Default language loaded',
    'language_system_error': 'Language system error',
    'language_preferences': 'Language Preferences',
    'auto_detect_language': 'Auto detect',
    'system_language': 'System language',
    'app_language': 'App language',
    'language_support': 'Language support',
    'multilingual_support': 'Multilingual support',
    'language_pack': 'Language pack',
    'translation_loading': 'Loading translations...',
    'translation_error': 'Translation error',
    'fallback_language': 'Fallback language',
    'language_code': 'Language code',
    'locale_settings': 'Locale settings',
    'regional_format': 'Regional format',
    'date_format': 'Date format',
    'number_format': 'Number format',
    'currency_format': 'Currency format',
    'time_format': 'Time format',
    
    // === LANGUAGE NAMES ===
    'spanish': 'Spanish',
    'english': 'English',
    'italian': 'Italian',
    'spanish_spain': 'Spanish (Spain)',
    'english_us': 'English (United States)',
    'english_uk': 'English (United Kingdom)',
    'italian_italy': 'Italian (Italy)',
    
    // === SYSTEM MESSAGES ===
    'loading': 'Loading...',
    'loading_data': 'Loading data...',
    'initializing': 'Initializing...',
    'please_wait': 'Please wait...',
    'processing': 'Processing...',
    'saving': 'Saving...',
    'loading_preferences': 'Loading preferences...',
    'applying_changes': 'Applying changes...',
    'updating_interface': 'Updating interface...',
    'preparing_content': 'Preparing content...',
    'loading_configuration': 'Loading configuration...',
    
    // === BUTTON ACTIONS ===
    'close': 'Close',
    'cancel': 'Cancel',
    'accept': 'Accept',
    'ok': 'Ok',
    'save': 'Save',
    'apply': 'Apply',
    'confirm': 'Confirm',
    'continue': 'Continue',
    'back': 'Back',
    'next': 'Next',
    'finish': 'Finish',
    'done': 'Done',
    'skip': 'Skip',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'reload': 'Reload',
    'reset': 'Reset',
    'clear': 'Clear',
    'delete': 'Delete',
    'edit': 'Edit',
    'view': 'View',
    'select': 'Select',
    'choose': 'Choose',
    'pick': 'Pick',
    'set': 'Set',
    'change': 'Change',
    'modify': 'Modify',
    'update': 'Update',
    'view_all': 'View all',
    
    // === STATES AND VALIDATIONS ===
    'success': 'Success',
    'error': 'Error',
    'warning': 'Warning',
    'info': 'Information',
    'completed': 'Completed',
    'failed': 'Failed',
    'pending': 'Pending',
    'in_progress': 'In progress',
    'cancelled': 'Cancelled',
    'timeout': 'Timeout',
    'unavailable': 'Unavailable',
    'not_found': 'Not found',
    'invalid': 'Invalid',
    'valid': 'Valid',
    'required_field': 'Required',
    'optional_field': 'Optional',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'active': 'Active',
    'inactive': 'Inactive',
    'online': 'Online',
    'offline': 'Offline',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'synchronized': 'Synchronized',
    'not_synchronized': 'Not synchronized',
    'sent': 'Sent',
    
    // === SPECIFIC ERROR MESSAGES ===
    'error_occurred': 'An error occurred',
    'unexpected_error': 'Unexpected error',
    'connection_error': 'Connection error',
    'network_error': 'Network error',
    'server_error': 'Server error',
    'data_error': 'Data error',
    'permission_error': 'Permission error',
    'configuration_error': 'Configuration error',
    'initialization_error': 'Initialization error',
    'validation_error': 'Validation error',
    'format_error': 'Format error',
    'compatibility_error': 'Compatibility error',
    'version_error': 'Version error',
    'memory_error': 'Memory error',
    'storage_error': 'Storage error',
    'file_error': 'File error',
    'database_error': 'Database error',
    'sync_error': 'Sync error',
    'backup_error': 'Backup error',
    'restore_error': 'Restore error',
    'import_error': 'Import error',
    'export_error': 'Export error',
    'parse_error': 'Parse error',
    'rendering_error': 'Rendering error',
    'calculation_error': 'Calculation error',
    'conversion_error': 'Conversion error',
    'error_loading_data': 'Error loading data',
    'no_data_available': 'No data available',
    'try_refresh': 'Try refreshing the data',
    
    // === CONFIGURATION AND PREFERENCES ===
    'settings': 'Settings',
    'preferences': 'Preferences',
    'options': 'Options',
    'configuration': 'Configuration',
    'setup': 'Setup',
    'customization': 'Customization',
    'appearance': 'Appearance',
    'behavior': 'Behavior',
    'notifications': 'Notifications',
    'privacy': 'Privacy',
    'security': 'Security',
    'accessibility': 'Accessibility',
    'advanced': 'Advanced',
    'general': 'General',
    'account': 'Account',
    'profile': 'Profile',
    'user_settings': 'User settings',
    'app_settings': 'App settings',
    'system_settings': 'System settings',
    'default_settings': 'Default settings',
    'restore_defaults': 'Restore defaults',
    'save_settings': 'Save settings',
    'settings_saved': 'Settings saved',
    'settings_restored': 'Settings restored',
    'unsaved_changes': 'Unsaved changes',
    'save_changes_question': 'Save changes?',
    'discard_changes': 'Discard changes',
    'changes_will_be_lost': 'Changes will be lost',
    
    // === ACCESSIBILITY ===
    'accessibility_enabled': 'Accessibility enabled',
    'high_contrast': 'High contrast',
    'large_text': 'Large text',
    'screen_reader': 'Screen reader',
    'voice_over': 'VoiceOver',
    'talk_back': 'TalkBack',
    'font_size': 'Font size',
    'text_size': 'Text size',
    'zoom_level': 'Zoom level',
    'contrast_level': 'Contrast level',
    'brightness': 'Brightness',
    'color_blind_support': 'Color blind support',
    'reduced_motion': 'Reduced motion',
    'audio_descriptions': 'Audio descriptions',
    'captions': 'Captions',
    'sign_language': 'Sign language',
    
    // === HELP AND SUPPORT ===
    'help': 'Help',
    'support': 'Support',
    'documentation': 'Documentation',
    'tutorial': 'Tutorial',
    'guide': 'Guide',
    'faq': 'FAQ',
    'contact': 'Contact',
    'feedback': 'Feedback',
    'report_bug': 'Report bug',
    'suggest_feature': 'Suggest feature',
    'user_manual': 'User manual',
    'quick_start': 'Quick start',
    'getting_started': 'Getting started',
    'tips_and_tricks': 'Tips and tricks',
    'troubleshooting': 'Troubleshooting',
    'known_issues': 'Known issues',
    'release_notes': 'Release notes',
    'changelog': 'Changelog',
    'version_info': 'Version info',
    'about': 'About',
    'legal': 'Legal',
    'terms_of_service': 'Terms of service',
    'privacy_policy': 'Privacy policy',
    'license': 'License',
    'credits': 'Credits',
    'acknowledgments': 'Acknowledgments',
    
    // === DASHBOARD AND NAVIGATION ===
    'dashboard': 'Dashboard',
    'home': 'Home',
    'menu': 'Menu',
    'navigation': 'Navigation',
    'sidebar': 'Sidebar',
    'toolbar': 'Toolbar',
    'header': 'Header',
    'footer': 'Footer',
    'main_content': 'Main content',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'group': 'Group',
    'categories': 'Categories',
    'tags': 'Tags',
    'favorites': 'Favorites',
    'bookmarks': 'Bookmarks',
    'recent': 'Recent',
    'history': 'History',
    'activity': 'Activity',
    'timeline': 'Timeline',
    'calendar': 'Calendar',
    'schedule': 'Schedule',
    'agenda': 'Agenda',
    'events': 'Events',
    'reminders': 'Reminders',
    'alerts': 'Alerts',
    'notifications_panel': 'Notifications panel',
    'status_bar': 'Status bar',
    'progress_bar': 'Progress bar',
    'loading_indicator': 'Loading indicator',
    'spinner': 'Spinner',
    
    // === TIME AND DATES ===
    'today': 'Today',
    'yesterday': 'Yesterday',
    'tomorrow': 'Tomorrow',
    'this_week': 'This week',
    'last_week': 'Last week',
    'next_week': 'Next week',
    'this_month': 'This month',
    'last_month': 'Last month',
    'next_month': 'Next month',
    'this_year': 'This year',
    'last_year': 'Last year',
    'next_year': 'Next year',
    'now': 'Now',
    'ago': 'ago',
    'in': 'in',
    'seconds': 'seconds',
    'minutes': 'minutes',
    'hours': 'hours',
    'days': 'days',
    'weeks': 'weeks',
    'months': 'months',
    'years': 'years',
    'second': 'second',
    'minute': 'minute',
    'hour': 'hour',
    'day': 'day',
    'week': 'week',
    'month': 'month',
    'year': 'year',
    'morning': 'morning',
    'afternoon': 'afternoon',
    'evening': 'evening',
    'night': 'night',
    'midnight': 'midnight',
    'noon': 'noon',
    'dawn': 'dawn',
    'dusk': 'dusk',
    'sunrise': 'sunrise',
    'sunset': 'sunset',
    
    // === DAYS OF THE WEEK ===
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'mon': 'Mon',
    'tue': 'Tue',
    'wed': 'Wed',
    'thu': 'Thu',
    'fri': 'Fri',
    'sat': 'Sat',
    'sun': 'Sun',
    
    // === MONTHS ===
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'jan': 'Jan',
    'feb': 'Feb',
    'mar': 'Mar',
    'apr': 'Apr',
    'may_short': 'May',
    'jun': 'Jun',
    'jul': 'Jul',
    'aug': 'Aug',
    'sep': 'Sep',
    'oct': 'Oct',
    'nov': 'Nov',
    'dec': 'Dec',
    
    // === APP SPECIFIC ===
    'app_name': 'My Inventory',
    'welcome': 'Welcome',
    'good_morning': 'Good morning',
    'good_afternoon': 'Good afternoon',
    'good_evening': 'Good evening',
    'products': 'Products',
    'inventory': 'Inventory',
    'sales': 'Sales',
    'reports': 'Reports',
    'point_of_sale': 'Point of Sale',
    'settings_app': 'Settings',
    
    // === DASHBOARD SPECIFIC ===
    'today_summary': 'Today\'s Summary',
    'sales_today': 'Sales Today',
    'active_products': 'active products',
    'low_stock': 'Low Stock',
    'require_attention': 'require attention',
    'detailed_analysis': 'detailed analysis',
    'quick_actions': 'Quick Actions',
    'new_sale': 'New Sale',
    'add_product': 'Add Product',
    'recent_sales': 'Recent Sales',
    'no_sales_recorded': 'No sales recorded',
    'sales_will_appear': 'Sales will appear here when registered',
    'system_working': 'System working',
    'store_ready': 'Store is ready to operate',
    
    // === PRODUCTS SPECIFIC ===
    'my_products': 'My Products',
    'product_name': 'Product Name',
    'product_description': 'Product Description',
    'category': 'Category',
    'no_category': 'No category',
    'select_category': 'Select category',
    'barcode': 'Barcode',
    'internal_code': 'Internal Code',
    'purchase_price': 'Purchase Price',
    'sale_price': 'Sale Price',
    'cost_price': 'Cost Price',
    'unit_measure': 'Unit of Measure',
    'minimum_stock': 'Minimum Stock',
    'current_stock': 'Current Stock',
    'initial_quantity': 'Initial Quantity',
    'product_information': 'Product Information',
    'stock_information': 'Stock Information',
    'price_information': 'Price Information',
    'code': 'Code',
    'description': 'Description',
    'unit': 'Unit',
    'stock': 'Stock',
    'price': 'Price',
    'margin': 'Margin',
    'profit_margin': 'Profit Margin',
    'stock_warning': 'Stock Warning',
    'low_stock_warning': 'Stock below recommended minimum',
    'out_of_stock': 'Out of Stock',
    'stock_ok': 'Normal Stock',
    'in_stock': 'In Stock',
    'stock_status': 'Stock Status',
    'add_stock': 'Add Stock',
    'edit_product': 'Edit Product',
    'new_product': 'New Product',
    'create_product': 'Create Product',
    'update_product': 'Update Product',
    'delete_product': 'Delete Product',
    'scan_barcode': 'Scan Barcode',
    'enter_barcode': 'Enter Barcode',
    'no_products_found': 'No products found',
    'no_products_registered': 'No products registered',
    'search_products': 'Search products',
    'filter_products': 'Filter products',
    'all_products': 'All products',
    'low_stock_products': 'Low stock products',
    'out_of_stock_products': 'Out of stock products',
    'sort_by_name': 'Sort by name',
    'sort_by_stock': 'Sort by stock',
    'sort_by_price': 'Sort by price',
    'clear_filters': 'Clear filters',
    'apply_filters': 'Apply filters',
    'product_created': 'Product created successfully',
    'product_updated': 'Product updated successfully',
    'product_deleted': 'Product deleted successfully',
    'error_creating_product': 'Error creating product',
    'error_updating_product': 'Error updating product',
    'error_deleting_product': 'Error deleting product',
    'product_details': 'Product Details',
    'basic_information': 'Basic Information',
    'pricing': 'Pricing',
    'stock_configuration': 'Stock Configuration',
    'unsaved_changes_product': 'You have unsaved changes',
    'discard_changes_product': 'Discard changes?',
    'save_changes_product': 'Save changes?',
    'continue_editing': 'Continue editing',
    'add_first_product': 'Add first product',
    'start_managing_inventory': 'Start managing your inventory',
    'product_codes': 'Product Codes',
    'expiration_date': 'Expiration Date',
    'select_date': 'Select date',
    'remove_date': 'Remove date',
    'notes': 'Notes',
    'observations': 'Observations',
    'batch_number': 'Batch Number',
    'batch_code': 'Batch Code',
    'batches': 'Batches',
    'no_batches': 'No batches',
    'add_batch': 'Add Batch',
    'expires': 'Expires',
    'expired': 'Expired',
    'near_expiry': 'Near expiry',
    'days_to_expire': 'days to expire',
    'expires_today': 'Expires today',
    'expires_tomorrow': 'Expires tomorrow',
    'no_expiration': 'No expiration date',
  };

  // ITALIANO
  static const Map<String, String> _italianTranslations = {
    // === CONFIGURAZIONE LINGUA ===
    'language': 'Lingua',
    'change_language': 'Cambia Lingua',
    'select_language': 'Seleziona Lingua',
    'language_changed': 'Lingua cambiata',
    'language_changed_successfully': 'Lingua cambiata con successo',
    'error_changing_language': 'Errore nel cambio lingua',
    'language_settings': 'Impostazioni Lingua',
    'current_language': 'Lingua Attuale',
    'available_languages': 'Lingue Disponibili',
    'language_selection': 'Selezione Lingua',
    'choose_preferred_language': 'Scegli la tua lingua preferita',
    'language_will_be_saved': 'La tua selezione lingua verrà salvata automaticamente',
    'restart_app_language': 'Riavvia l\'app per applicare completamente il cambiamento',
    'language_applied': 'Lingua applicata',
    'loading_language': 'Caricamento lingua...',
    'language_not_available': 'Lingua non disponibile',
    'default_language_loaded': 'Lingua predefinita caricata',
    'language_system_error': 'Errore sistema lingua',
    'language_preferences': 'Preferenze Lingua',
    'auto_detect_language': 'Rilevamento automatico',
    'system_language': 'Lingua del sistema',
    'app_language': 'Lingua dell\'app',
    'language_support': 'Supporto linguistico',
    'multilingual_support': 'Supporto multilingue',
    'language_pack': 'Pacchetto lingua',
    'translation_loading': 'Caricamento traduzioni...',
    'translation_error': 'Errore traduzione',
    'fallback_language': 'Lingua di fallback',
    'language_code': 'Codice lingua',
    'locale_settings': 'Impostazioni localizzazione',
    'regional_format': 'Formato regionale',
    'date_format': 'Formato data',
    'number_format': 'Formato numerico',
    'currency_format': 'Formato valuta',
    'time_format': 'Formato ora',
    
    // === NOMI LINGUE ===
    'spanish': 'Spagnolo',
    'english': 'Inglese',
    'italian': 'Italiano',
    'spanish_spain': 'Spagnolo (Spagna)',
    'english_us': 'Inglese (Stati Uniti)',
    'english_uk': 'Inglese (Regno Unito)',
    'italian_italy': 'Italiano (Italia)',
    
    // === MESSAGGI SISTEMA ===
    'loading': 'Caricamento...',
    'loading_data': 'Caricamento dati...',
    'initializing': 'Inizializzazione...',
    'please_wait': 'Attendi per favore...',
    'processing': 'Elaborazione...',
    'saving': 'Salvataggio...',
    'loading_preferences': 'Caricamento preferenze...',
    'applying_changes': 'Applicazione modifiche...',
    'updating_interface': 'Aggiornamento interfaccia...',
    'preparing_content': 'Preparazione contenuto...',
    'loading_configuration': 'Caricamento configurazione...',
    
    // === AZIONI PULSANTI ===
    'close': 'Chiudi',
    'cancel': 'Annulla',
    'accept': 'Accetta',
    'ok': 'Ok',
    'save': 'Salva',
    'apply': 'Applica',
    'confirm': 'Conferma',
    'continue': 'Continua',
    'back': 'Indietro',
    'next': 'Avanti',
    'finish': 'Termina',
    'done': 'Fatto',
    'skip': 'Salta',
    'retry': 'Riprova',
    'refresh': 'Aggiorna',
    'reload': 'Ricarica',
    'reset': 'Ripristina',
    'clear': 'Cancella',
    'delete': 'Elimina',
    'edit': 'Modifica',
    'view': 'Visualizza',
    'select': 'Seleziona',
    'choose': 'Scegli',
    'pick': 'Prendi',
    'set': 'Imposta',
    'change': 'Cambia',
    'modify': 'Modifica',
    'update': 'Aggiorna',
    'view_all': 'Vedi tutto',
    
    // === STATI E VALIDAZIONI ===
    'success': 'Successo',
    'error': 'Errore',
    'warning': 'Avviso',
    'info': 'Informazioni',
    'completed': 'Completato',
    'failed': 'Fallito',
    'pending': 'In attesa',
    'in_progress': 'In corso',
    'cancelled': 'Annullato',
    'timeout': 'Timeout',
    'unavailable': 'Non disponibile',
    'not_found': 'Non trovato',
    'invalid': 'Non valido',
    'valid': 'Valido',
    'required_field': 'Richiesto',
    'optional_field': 'Opzionale',
    'enabled': 'Abilitato',
    'disabled': 'Disabilitato',
    'active': 'Attivo',
    'inactive': 'Inattivo',
    'online': 'Online',
    'offline': 'Offline',
    'connected': 'Connesso',
    'disconnected': 'Disconnesso',
    'synchronized': 'Sincronizzato',
    'not_synchronized': 'Non sincronizzato',
    'sent': 'Inviato',
    
    // === MESSAGGI ERRORE SPECIFICI ===
    'error_occurred': 'Si è verificato un errore',
    'unexpected_error': 'Errore inaspettato',
    'connection_error': 'Errore di connessione',
    'network_error': 'Errore di rete',
    'server_error': 'Errore del server',
    'data_error': 'Errore dati',
    'permission_error': 'Errore permessi',
    'configuration_error': 'Errore configurazione',
    'initialization_error': 'Errore inizializzazione',
    'validation_error': 'Errore validazione',
    'format_error': 'Errore formato',
    'compatibility_error': 'Errore compatibilità',
    'version_error': 'Errore versione',
    'memory_error': 'Errore memoria',
    'storage_error': 'Errore archiviazione',
    'file_error': 'Errore file',
    'database_error': 'Errore database',
    'sync_error': 'Errore sincronizzazione',
    'backup_error': 'Errore backup',
    'restore_error': 'Errore ripristino',
    'import_error': 'Errore importazione',
    'export_error': 'Errore esportazione',
    'parse_error': 'Errore analisi',
    'rendering_error': 'Errore rendering',
    'calculation_error': 'Errore calcolo',
    'conversion_error': 'Errore conversione',
    'error_loading_data': 'Errore caricamento dati',
    'no_data_available': 'Nessun dato disponibile',
    'try_refresh': 'Prova ad aggiornare i dati',
    
    // === CONFIGURAZIONE E PREFERENZE ===
    'settings': 'Impostazioni',
    'preferences': 'Preferenze',
    'options': 'Opzioni',
    'configuration': 'Configurazione',
    'setup': 'Configurazione iniziale',
    'customization': 'Personalizzazione',
    'appearance': 'Aspetto',
    'behavior': 'Comportamento',
    'notifications': 'Notifiche',
    'privacy': 'Privacy',
    'security': 'Sicurezza',
    'accessibility': 'Accessibilità',
    'advanced': 'Avanzate',
    'general': 'Generale',
    'account': 'Account',
    'profile': 'Profilo',
    'user_settings': 'Impostazioni utente',
    'app_settings': 'Impostazioni app',
    'system_settings': 'Impostazioni sistema',
    'default_settings': 'Impostazioni predefinite',
    'restore_defaults': 'Ripristina predefinite',
    'save_settings': 'Salva impostazioni',
    'settings_saved': 'Impostazioni salvate',
    'settings_restored': 'Impostazioni ripristinate',
    'unsaved_changes': 'Modifiche non salvate',
    'save_changes_question': 'Salvare le modifiche?',
    'discard_changes': 'Scarta modifiche',
    'changes_will_be_lost': 'Le modifiche andranno perse',
    
    // === ACCESSIBILITÀ ===
    'accessibility_enabled': 'Accessibilità abilitata',
    'high_contrast': 'Alto contrasto',
    'large_text': 'Testo grande',
    'screen_reader': 'Lettore schermo',
    'voice_over': 'VoiceOver',
    'talk_back': 'TalkBack',
    'font_size': 'Dimensione carattere',
    'text_size': 'Dimensione testo',
    'zoom_level': 'Livello zoom',
    'contrast_level': 'Livello contrasto',
    'brightness': 'Luminosità',
    'color_blind_support': 'Supporto daltonismo',
    'reduced_motion': 'Movimento ridotto',
    'audio_descriptions': 'Descrizioni audio',
    'captions': 'Sottotitoli',
    'sign_language': 'Linguaggio dei segni',
    
    // === AIUTO E SUPPORTO ===
    'help': 'Aiuto',
    'support': 'Supporto',
    'documentation': 'Documentazione',
    'tutorial': 'Tutorial',
    'guide': 'Guida',
    'faq': 'FAQ',
    'contact': 'Contatto',
    'feedback': 'Feedback',
    'report_bug': 'Segnala bug',
    'suggest_feature': 'Suggerisci funzione',
    'user_manual': 'Manuale utente',
    'quick_start': 'Avvio rapido',
    'getting_started': 'Primi passi',
    'tips_and_tricks': 'Suggerimenti e trucchi',
    'troubleshooting': 'Risoluzione problemi',
    'known_issues': 'Problemi noti',
    'release_notes': 'Note di rilascio',
    'changelog': 'Registro modifiche',
    'version_info': 'Info versione',
    'about': 'Informazioni',
    'legal': 'Legale',
    'terms_of_service': 'Termini di servizio',
    'privacy_policy': 'Privacy policy',
    'license': 'Licenza',
    'credits': 'Crediti',
    'acknowledgments': 'Riconoscimenti',
    
    // === DASHBOARD E NAVIGAZIONE ===
    'dashboard': 'Pannello di Controllo',
    'home': 'Home',
    'menu': 'Menu',
    'navigation': 'Navigazione',
    'sidebar': 'Barra laterale',
    'toolbar': 'Barra strumenti',
    'header': 'Intestazione',
    'footer': 'Piè di pagina',
    'main_content': 'Contenuto principale',
    'search': 'Cerca',
    'filter': 'Filtra',
    'sort': 'Ordina',
    'group': 'Raggruppa',
    'categories': 'Categorie',
    'tags': 'Tag',
    'favorites': 'Preferiti',
    'bookmarks': 'Segnalibri',
    'recent': 'Recente',
    'history': 'Cronologia',
    'activity': 'Attività',
    'timeline': 'Timeline',
    'calendar': 'Calendario',
    'schedule': 'Programma',
    'agenda': 'Agenda',
    'events': 'Eventi',
    'reminders': 'Promemoria',
    'alerts': 'Avvisi',
    'notifications_panel': 'Pannello notifiche',
    'status_bar': 'Barra stato',
    'progress_bar': 'Barra progresso',
    'loading_indicator': 'Indicatore caricamento',
    'spinner': 'Spinner',
    
    // === TEMPO E DATE ===
    'today': 'Oggi',
    'yesterday': 'Ieri',
    'tomorrow': 'Domani',
    'this_week': 'Questa settimana',
    'last_week': 'Settimana scorsa',
    'next_week': 'Prossima settimana',
    'this_month': 'Questo mese',
    'last_month': 'Mese scorso',
    'next_month': 'Prossimo mese',
    'this_year': 'Quest\'anno',
    'last_year': 'Anno scorso',
    'next_year': 'Prossimo anno',
    'now': 'Ora',
    'ago': 'fa',
    'in': 'tra',
    'seconds': 'secondi',
    'minutes': 'minuti',
    'hours': 'ore',
    'days': 'giorni',
    'weeks': 'settimane',
    'months': 'mesi',
    'years': 'anni',
    'second': 'secondo',
    'minute': 'minuto',
    'hour': 'ora',
    'day': 'giorno',
    'week': 'settimana',
    'month': 'mese',
    'year': 'anno',
    'morning': 'mattina',
    'afternoon': 'pomeriggio',
    'evening': 'sera',
    'night': 'notte',
    'midnight': 'mezzanotte',
    'noon': 'mezzogiorno',
    'dawn': 'alba',
    'dusk': 'tramonto',
    'sunrise': 'alba',
    'sunset': 'tramonto',
    
    // === GIORNI DELLA SETTIMANA ===
    'monday': 'Lunedì',
    'tuesday': 'Martedì',
    'wednesday': 'Mercoledì',
    'thursday': 'Giovedì',
    'friday': 'Venerdì',
    'saturday': 'Sabato',
    'sunday': 'Domenica',
    'mon': 'Lun',
    'tue': 'Mar',
    'wed': 'Mer',
    'thu': 'Gio',
    'fri': 'Ven',
    'sat': 'Sab',
    'sun': 'Dom',
    
    // === MESI ===
    'january': 'Gennaio',
    'february': 'Febbraio',
    'march': 'Marzo',
    'april': 'Aprile',
    'may': 'Maggio',
    'june': 'Giugno',
    'july': 'Luglio',
    'august': 'Agosto',
    'september': 'Settembre',
    'october': 'Ottobre',
    'november': 'Novembre',
    'december': 'Dicembre',
    'jan': 'Gen',
    'feb': 'Feb',
    'mar': 'Mar',
    'apr': 'Apr',
    'may_short': 'Mag',
    'jun': 'Giu',
    'jul': 'Lug',
    'aug': 'Ago',
    'sep': 'Set',
    'oct': 'Ott',
    'nov': 'Nov',
    'dec': 'Dic',
    
    // === APP SPECIFICO ===
    'app_name': 'Il Mio Inventario',
    'welcome': 'Benvenuto',
    'good_morning': 'Buongiorno',
    'good_afternoon': 'Buon pomeriggio',
    'good_evening': 'Buonasera',
    'products': 'Prodotti',
    'inventory': 'Inventario',
    'sales': 'Vendite',
    'reports': 'Rapporti',
    'point_of_sale': 'Punto Vendita',
    'settings_app': 'Impostazioni',
    
    // === DASHBOARD SPECIFICO ===
    'today_summary': 'Riepilogo di Oggi',
    'sales_today': 'Vendite di Oggi',
    'active_products': 'prodotti attivi',
    'low_stock': 'Scorte Basse',
    'require_attention': 'richiedono attenzione',
    'detailed_analysis': 'analisi dettagliata',
    'quick_actions': 'Azioni Rapide',
    'new_sale': 'Nuova Vendita',
    'add_product': 'Aggiungi Prodotto',
    'recent_sales': 'Vendite Recenti',
    'no_sales_recorded': 'Nessuna vendita registrata',
    'sales_will_appear': 'Le vendite appariranno qui quando registrate',
    'system_working': 'Sistema funzionante',
    'store_ready': 'Il negozio è pronto per operare',
    
    // === PRODOTTI SPECIFICO ===
    'my_products': 'I Miei Prodotti',
    'product_name': 'Nome del Prodotto',
    'product_description': 'Descrizione del Prodotto',
    'category': 'Categoria',
    'no_category': 'Nessuna categoria',
    'select_category': 'Seleziona categoria',
    'barcode': 'Codice a Barre',
    'internal_code': 'Codice Interno',
    'purchase_price': 'Prezzo di Acquisto',
    'sale_price': 'Prezzo di Vendita',
    'cost_price': 'Prezzo di Costo',
    'unit_measure': 'Unità di Misura',
    'minimum_stock': 'Scorte Minime',
    'current_stock': 'Scorte Attuali',
    'initial_quantity': 'Quantità Iniziale',
    'product_information': 'Informazioni del Prodotto',
    'stock_information': 'Informazioni delle Scorte',
    'price_information': 'Informazioni sui Prezzi',
    'code': 'Codice',
    'description': 'Descrizione',
    'unit': 'Unità',
    'stock': 'Scorte',
    'price': 'Prezzo',
    'margin': 'Margine',
    'profit_margin': 'Margine di Profitto',
    'stock_warning': 'Avviso Scorte',
    'low_stock_warning': 'Scorte sotto il minimo raccomandato',
    'out_of_stock': 'Esaurito',
    'stock_ok': 'Scorte Normali',
    'in_stock': 'Disponibile',
    'stock_status': 'Stato delle Scorte',
    'add_stock': 'Aggiungi Scorte',
    'edit_product': 'Modifica Prodotto',
    'new_product': 'Nuovo Prodotto',
    'create_product': 'Crea Prodotto',
    'update_product': 'Aggiorna Prodotto',
    'delete_product': 'Elimina Prodotto',
    'scan_barcode': 'Scansiona Codice',
    'enter_barcode': 'Inserisci Codice',
    'no_products_found': 'Nessun prodotto trovato',
    'no_products_registered': 'Nessun prodotto registrato',
    'search_products': 'Cerca prodotti',
    'filter_products': 'Filtra prodotti',
    'all_products': 'Tutti i prodotti',
    'low_stock_products': 'Prodotti con scorte basse',
    'out_of_stock_products': 'Prodotti esauriti',
    'sort_by_name': 'Ordina per nome',
    'sort_by_stock': 'Ordina per scorte',
    'sort_by_price': 'Ordina per prezzo',
    'clear_filters': 'Cancella filtri',
    'apply_filters': 'Applica filtri',
    'product_created': 'Prodotto creato con successo',
    'product_updated': 'Prodotto aggiornato con successo',
    'product_deleted': 'Prodotto eliminato con successo',
    'error_creating_product': 'Errore nella creazione del prodotto',
    'error_updating_product': 'Errore nell\'aggiornamento del prodotto',
    'error_deleting_product': 'Errore nell\'eliminazione del prodotto',
    'product_details': 'Dettagli del Prodotto',
    'basic_information': 'Informazioni Base',
    'pricing': 'Prezzi',
    'stock_configuration': 'Configurazione Scorte',
    'unsaved_changes_product': 'Hai modifiche non salvate',
    'discard_changes_product': 'Scartare le modifiche?',
    'save_changes_product': 'Salvare le modifiche?',
    'continue_editing': 'Continua modifica',
    'add_first_product': 'Aggiungi primo prodotto',
    'start_managing_inventory': 'Inizia a gestire il tuo inventario',
    'product_codes': 'Codici del Prodotto',
    'expiration_date': 'Data di Scadenza',
    'select_date': 'Seleziona data',
    'remove_date': 'Rimuovi data',
    'notes': 'Note',
    'observations': 'Osservazioni',
    'batch_number': 'Numero di Lotto',
    'batch_code': 'Codice Lotto',
    'batches': 'Lotti',
    'no_batches': 'Nessun lotto',
    'add_batch': 'Aggiungi Lotto',
    'expires': 'Scade',
    'expired': 'Scaduto',
    'near_expiry': 'Prossimo alla scadenza',
    'days_to_expire': 'giorni alla scadenza',
    'expires_today': 'Scade oggi',
    'expires_tomorrow': 'Scade domani',
    'no_expiration': 'Nessuna data di scadenza',
  };
}

// Clase para información de idiomas
class LanguageInfo {
  final String name;
  final String flag;
  
  const LanguageInfo(this.name, this.flag);
}